(setq user-full-name "entertainyou")
(setq user-mail-address "grubbyfans@gmail.com")

;; (setq bookmark-default-file "~/.emacs.d/.emacs.bmk")

;; (setq abbrev-file-name "~/.emacs.d/.abbrev_defs")

(setq load-path (cons "~/.emacs.d/" load-path))

(load "emacs-basic")
(load "emacs-programming")
(load "emacs-autoheader")
;; (load "emacs-tramp")
;; (load "emacs-language")
;; (load "emacs-calendar")
;; (load "emacs-folding")
;; (load "emacs-ido")
;; (load "emacs-dictionary")
;; (load "emacs-function")
;; (load "emacs-cedet")
;; (load "emacs-org")
;; (load "emacs-key-bindings")
;; (load "jerry-dired")
;; (load "jerry-mode")
;; (load "jerry-wiki")
;; (load "jerry-other-elisp")
;; (load "jerry-key-bindings")

;; (load "desktop")						
;; (desktop-save-mode)
;; (desktop-read)
